export type Envs =
  | "AZURE_CLIENT_ID"
  | "AZURE_CLIENT_SECRET"
  | "AZURE_TENANT_ID"
  | "CROUTON_AZURE_KEY_VAULT_NAME"
  | "CROUTON_PIXELA_ACCESS_TOKEN"
  | "CROUTON_PIXELA_GRAPH_ID"
  | "CROUTON_PIXELA_USERNAME"
  | "CROUTON_TIME_DIFFERENCE"
  | "CROUTON_TWITTER_ACCESS_TOKENS"
  | "CROUTON_TWITTER_ACCESS_TOKEN_SECRETS"
  | "CROUTON_TWITTER_CONSUMER_KEY"
  | "CROUTON_TWITTER_CONSUMER_SECRET"
  | "CROUTON_TWITTER_FORMAT"
  | "CROUTON_TWITTER_ID";

export namespace TwitterResponse {
  export type Status = {
    created_at: string;
    id_str: string;
  };
}
